### ISSUE TITLE
新規ユーザーがログインした時点でfirebaseにデータを作成する

### ISSUE THREAD

**Issue by Kasanomo** [Kasanomo/vue-sg-hackvote#6]

**Comment by Kasanomo** [comment]
この時点でinitializeして、vote内ではupdateのみ行う

**Comment by kusumoto-jp** [comment]
話してて分かったこと：ログイン時点で空のデータを作るためにはチーム名が分かってないといけない

→ログイン時点では User ID をLocalStorageに
→投票画面で User ID を元に、投票済みかどうかで条件分岐
